name: Docker Image CI

on:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login
      run: docker login -u admin44449999 -p Aaryanaryan
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64 . -t admin44449999/toy3:latest --push
